"""Matched-measurement joint 4D versus independent 3D TBMD ablation.

P1/P2 and all folds use the canonical training-only scaling. The first 10 or all
30 configured wells supply BOTH properties to every model, removing placement
as a confounder. Independent models use either r atoms per property (more total
coefficients) or split the joint r between properties (equal total coefficients).
Spatial ranks and estimators are unchanged. Neither capacity comparison alone
isolates every modelling choice; both are reported, without test-set tuning.
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import tensorly as tl
from tensorly.decomposition import tucker

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from bss import OUT, load_config
from bss import bases, data, estimators, metrics, parallel


def single_basis(train, ij, rank, cfg):
    grid = np.zeros((139, 48, train.shape[1]))
    grid[ij[:, 0], ij[:, 1]] = train
    ranks = [cfg["tbmd_spatial_ranks"][0], cfg["tbmd_spatial_ranks"][1], rank]
    core, factors = tucker(grid, rank=ranks, random_state=0, **cfg["tucker"])
    modes = tl.tenalg.multi_mode_dot(core, factors[:2], modes=[0, 1])
    return modes[ij[:, 0], ij[:, 1]]


def job(protocol, index):
    cfg = load_config()
    b = data.load(cfg["dataset"], cfg["wells"])
    fold = (data.folds_p1(b, cfg["train_fraction_p1"]) if protocol == "P1"
            else data.folds_p2(b))[index]
    n = b.n_active
    rank = bases.pod(fold.train, threshold=cfg["energy_threshold"]).extra["rank"]
    joint = bases.tbmd(fold.train, b.ij, rank,
                       spatial_ranks=cfg["tbmd_spatial_ranks"], **cfg["tucker"]).B
    models = {"joint-4D": (joint, rank, rank)}
    cache = {}
    for label, ranks in (("independent-equal-total", (rank // 2, rank - rank // 2)),
                         ("independent-per-property", (rank, rank))):
        basis = np.zeros((2 * n, sum(ranks)))
        offset = 0
        for prop, depth in enumerate(ranks):
            if (prop, depth) not in cache:
                cache[prop, depth] = single_basis(fold.train[prop*n:(prop+1)*n], b.ij, depth, cfg)
            basis[prop*n:(prop+1)*n, offset:offset+depth] = cache[prop, depth]
            offset += depth
        models[label] = (basis, *ranks)
    records = []
    for budget in (10, 30):
        rows = np.concatenate([b.well_rows[:budget], b.well_rows[:budget] + n])
        observations = fold.test[rows]
        for model, (basis, rp, rs) in models.items():
            for estimator in ("LS", "L1"):
                if estimator == "LS":
                    coef = estimators.least_squares(basis[rows], observations, cfg["ls_rcond"])
                    iterations = 0
                else:
                    coef, iterations = estimators.l1_admm(basis[rows], observations, **cfg["l1"])
                score = metrics.evaluate(basis @ coef, fold, n)
                records.append(dict(protocol=protocol, fold=fold.name, model=model,
                    estimator=estimator, wells=budget, channels=len(rows), joint_rank=rank,
                    rank_pressure=rp, rank_so=rs, coefficients=basis.shape[1],
                    rmse_p=float(score["rmse_p"].mean()), rmse_so=float(score["rmse_so"].mean()),
                    admm_iterations=iterations))
    print(f"E8 {fold.name} complete", flush=True)
    return records


def summarise():
    frame = pd.read_csv(OUT / "e8_property_coupling.csv")
    group = ["protocol", "wells", "model", "estimator"]
    summary = frame.groupby(group)[["rmse_p", "rmse_so"]].agg(["mean", "std"])
    summary.columns = ["_".join(c) for c in summary.columns]
    summary.to_csv(OUT / "e8_property_coupling_summary.csv")
    lines = [r"% Generated by e8_property_coupling.py; do not edit.",
             r"\begin{table}[htbp]\centering\small",
             r"\caption{Matched-measurement property-coupling ablation (E8), P2, all 30 wells (60 channels). Mean $\pm$ sample standard deviation over ten held-out scenarios; RMSE is averaged over snapshots within each fold. All models use the same measurements and spatial ranks $(48,48)$. The two independent controls use equal total or equal per-property coefficient counts.}",
             r"\label{tab:S_coupling}", r"\begin{tabular}{lrrr}\toprule",
             r"Model / estimator & Coefficients & Pressure ($u_p$) & $S_o$ ($10^{-3}$) \\\midrule"]
    labels = {"joint-4D": "Joint 4D", "independent-equal-total": "Independent, total",
              "independent-per-property": "Independent, per property"}
    for (protocol, budget, model, estimator), row in summary.iterrows():
        if protocol != "P2" or budget != 30:
            continue
        count = frame[(frame.protocol == protocol) & (frame.model == model)].coefficients.unique()
        assert len(count) == 1
        est = "LS" if estimator == "LS" else r"$\ell_1$"
        p = f"${row.rmse_p_mean:.3f} \\pm {row.rmse_p_std:.3f}$"
        s = f"${1000*row.rmse_so_mean:.3f} \\pm {1000*row.rmse_so_std:.3f}$"
        lines.append(f"{labels[model]} / {est} & {count[0]} & {p} & {s} " + r"\\")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    (OUT / "tabS_coupling.tex").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    if sys.argv[1] == "part":
        protocol, index = sys.argv[2], int(sys.argv[3])
        parallel.save_part("e8", f"{protocol}-{index:02d}", job(protocol, index))
    elif sys.argv[1] == "merge":
        records = [row for _, rows in parallel.load_parts("e8") for row in rows]
        assert len(records) == 240, f"Incomplete E8: {len(records)} rows"
        pd.DataFrame(records).to_csv(OUT / "e8_property_coupling.csv", index=False)
        summarise()
    elif sys.argv[1] == "summarise":
        summarise()
    else:
        raise SystemExit("Expected part PROTOCOL INDEX, merge, or summarise")
