"""Generate manuscript macros from canonical E9 outputs."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from bss import OUT  # noqa: E402

DEST = OUT / "e9_property_mode"


def main() -> None:
    summary = pd.read_csv(DEST / "outer_summary.csv")
    selected = pd.read_csv(DEST / "outer_selected_results.csv")
    decision = json.loads((DEST / "decision.json").read_text())
    coupling = json.loads((DEST / "cross_property_structure_summary.json").read_text())

    def row(method: str, capacity: str, geometry: str, budget: int) -> pd.Series:
        match = summary[
            (summary.model_label == method)
            & (summary.capacity_regime == capacity)
            & (summary.geometry == geometry)
            & (summary.budget == budget)
        ]
        if len(match) != 1:
            raise ValueError((method, capacity, geometry, budget, len(match)))
        return match.iloc[0]

    macros: dict[str, str] = {
        "ENineRepresentationRows": str(len(pd.read_csv(DEST / "inner_representation_registry.csv"))),
        "ENineSparseRows": str(len(pd.read_csv(DEST / "inner_sparse_registry.csv"))),
        "ENineOuterRows": str(len(pd.read_csv(DEST / "outer_results.csv"))),
        "ENineHeadlineAdvantages": str(decision["headline_advantages"]),
        "ENineHeadlineComparisons": str(decision["headline_comparisons"]),
        "ENineRankingDifferences": str(decision["ranking_difference_regimes"]),
        "ENineRankingRegimes": str(decision["ranking_regimes_total"]),
        "ENineAnomalyCorrelation": f"{coupling['anomaly_pearson']['mean']:.3f}",
        "ENineTemporalCorrelation": f"{coupling['temporal_spatial_mean_pearson']['mean']:.3f}",
        "ENineSubspaceAlignment": f"{coupling['subspace_cosine_mean_16']['mean']:.3f}",
        "ENineRankOneEnergy": f"{coupling['property_rank1_energy']['mean']:.3f}",
    }
    locations = {
        "Full": ("full", 9900),
        "WellFive": ("wells", 5),
        "WellFifteen": ("wells", 15),
        "WellThirty": ("wells", 30),
        "GridThirty": ("grid", 30),
        "GridThreeHundred": ("grid", 300),
    }
    metrics = {
        "ErrorP": "anomaly_relative_frobenius_p_mean",
        "ErrorSo": "anomaly_relative_frobenius_so_mean",
        "SsimP": "anomaly_ssim_p_mean",
        "SsimSo": "anomaly_ssim_so_mean",
        "RmseP": "rmse_p_mean",
        "RmseSo": "rmse_so_mean",
    }
    for location, (geometry, budget) in locations.items():
        for method_name, method in (("Three", "3D optimized"), ("Four", "4D optimized")):
            record = row(method, "equal_total", geometry, budget)
            for suffix, column in metrics.items():
                precision = 4 if suffix in {"RmseSo"} else 3
                macros[f"ENine{location}{method_name}{suffix}"] = (
                    f"{record[column]:.{precision}f}"
                )
            macros[f"ENine{location}{method_name}Storage"] = f"{record.storage_floats_mean:.0f}"
    sparse_4d = selected[
        (selected.model_label == "4D optimized") & (selected.geometry != "full")
    ]
    macros["ENineSharedHeadSelections"] = str(
        int((sparse_4d.pair_4d_variant == "4D-B").sum())
    )
    macros["ENineSparseSelections"] = str(len(sparse_4d))
    headline_metrics = {
        "anomaly_relative_frobenius_p",
        "anomaly_relative_frobenius_so",
        "anomaly_ssim_p",
        "anomaly_ssim_so",
    }
    current = pd.read_csv(DEST / "paired_comparisons.csv").query(
        "comparison == 'current'"
    )
    macros["ENineCurrentAdvantages"] = str(
        int(current[current.metric.isin(headline_metrics)].empirical_advantage.sum())
    )
    lines = ["% Generated by e9_make_numbers.py; do not edit."]
    lines.extend(f"\\newcommand{{\\{key}}}{{{value}}}" for key, value in macros.items())
    (DEST / "e9_numbers.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {len(macros)} E9 manuscript macros")


if __name__ == "__main__":
    main()
