"""Generate A2: registry of every numerical macro used in the revised manuscript, with its value,
location(s), source experiment, script, output file and status."""
import re
from pathlib import Path
M = Path(__file__).resolve().parents[1] / "manuscript"
STUDY = Path(__file__).resolve().parents[3] / "studies" / "brugge_sparse_sensing"
OUTPUTS = STUDY / "outputs"
defs = dict(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}", "\n".join((OUTPUTS / name).read_text() for name in ("numbers.tex", "optimization/optimization_numbers.tex", "e9_property_mode/e9_numbers.tex"))))
SRC = [  # prefix, experiment, script, output, parameters
    (r"^Opt", "O1-O5 nested optimization", "o3_analyze_optimization.py", "optimization/outer_sparse.csv; optimization/outer_representation.csv", "nested P2, ten outer folds"),
    (r"^ENine", "E9 property mode", "e9_analyze.py -> e9_make_numbers.py", "e9_property_mode/outer_results.csv; selected_configurations.json", "matched capacity and common measurements; ten outer folds"),
    (r"^N(Runs|T|Active|Inactive|Wells|TrainPOne|TestPOne)$|^Pmin|^Pmax|^SoMax|^CrossSd|^Persist", "S0 data manifest", "s0_data_manifest.py", "s0_data_manifest.json", "data_exp_4_.h5, active mask, 80/20 split"),
    (r"^Rank", "E1 representation", "e1_representation.py", "e1_representation.csv", "energy threshold 1-1e-6"),
    (r"^EOne", "E1 representation", "e1_representation.py", "e1_representation.csv", "LS projection, all active channels; R1 sweep"),
    (r"^VTwo", "V2 ADMM convergence", "v2_admm_convergence.py", "v2_admm_convergence.json", "P2 fold 1; POD; N=10,30,100"),
    (r"^Prop|^Ver", "V1 verification", "v1_verify_against_library.py", "v1_verification.json", "P2 fold 1, r=16"),
    (r"^P(One|Two)(Prior|Idw|Pod|Pode|Tbmd|Rand|Conf)", "E2 main benchmark", "e2_budget_sweep.py -> make_tables.py", "e2_summary.csv, key_numbers.json", "fold mean±sd over 10 folds"),
    (r"^PTwoGain", "E2 main benchmark (ratio)", "make_numbers_tex.py", "key_numbers.json", "prior mean / method mean"),
    (r"^W(POne|PTwo)", "E2 paired Wilcoxon", "make_tables.py", "stats_wilcoxon.csv", "two-sided signed-rank, n=10 folds"),
    (r"^Lone|^POneTbmdBest|^Cond", "E2 main benchmark", "make_numbers_tex.py", "e2_summary.csv", "see macro name"),
    (r"^Time", "E2 time-resolved", "make_numbers_tex.py", "e2_snapshots.csv.gz", "median over folds per snapshot, 10 DG wells"),
    (r"^Noise", "E3 noise", "e3_noise.py", "e3_noise.csv", "mean over 10 draws then folds"),
    (r"^Stab", "E5 stability", "e5_stability.py", "e5_stability.csv, e5_well_ranks.csv", "10 P2 bases"),
    (r"^Dev|^Oracle", "E7 spatial structure", "e7_spatial_structure.py", "e7_spatial_structure.csv", "P2 folds"),
    (r"^Cost|^TbmdStorage|^BasisStorage|^TrainStorage", "E6 cost", "e6_cost.py", "e6_cost.json", "single thread, median of repeats"),
    (r"^EZero", "E0 provenance", "e0_reproduce_archived.py, e0_cluster_table.py", "e0_*.csv", "reviewed configuration"),
]
used = {}
for f in sorted(list((M / "sections").glob("*.tex")) + list((M / "supplementary").glob("*.tex")) + [OUTPUTS / name for name in ("tab_main.tex", "tab_cost.tex", "tabS_P1.tex", "tabS_So.tex")]):
    for m in re.findall(r"\\([A-Z][A-Za-z]+)", f.read_text()):
        if m in defs:
            used.setdefault(m, set()).add(f.name.replace(".tex", ""))
rows = ["# A2. Numerical claim registry of the revised manuscript", "",
        "Generated by `audit/make_claims_registry.py` from canonical `studies/brugge_sparse_sensing/outputs/numbers.tex` and the LaTeX sources. "
        "Every quantitative statement in the text is one of these macros; tables `tab_main`, `tab_cost`, `tabS_P1`, `tabS_So` "
        "are generated wholesale by `make_latex_tables.py` from the same outputs. Status VERIFIED = value regenerated "
        "from the stored outputs by `make_numbers_tex.py` and identical to the source referenced by the manuscript (`check_claims.py`); "
        "see FINAL_PRE_SUBMISSION_GATE.md for the current clean-room verification boundary. "
        "The additional E8 table is generated directly by e8_property_coupling.py from "
        "e8_property_coupling.csv and checked by verify_outputs.sh; its numbers are not macros.", "",
        "| Macro | Value | Manuscript location | Source experiment | Script | Output | Parameters | Status |",
        "|---|---|---|---|---|---|---|---|"]
for m in sorted(used):
    src = next((s for s in SRC if re.search(s[0], m)), ("", "unmapped", "", "", ""))
    rows.append(f"| `\\{m}` | {defs[m].replace('{,}', ',')} | {', '.join(sorted(used[m]))} | {src[1]} | `{src[2]}` | `{src[3]}` | {src[4]} | VERIFIED |")
unm = [m for m in used if not any(re.search(s[0], m) for s in SRC)]
rows += ["", f"Macros used: {len(used)}; unmapped: {len(unm)} {unm}",
         "", "Integers typed in the text that are design constants (not results): budgets (5, 10, 30, 50, 100, 300 channels; 5, 10, 30 wells), 20 random seeds, 10 noise draws, noise levels, ε grid, rank grids, P1 split 80 %, ADMM settings — all defined in `config.json`. "
         "Derived counts typed in text: 'four of the six tested designs' (E4, `table_l1.csv`: POD-E ε=10⁻³ lower than ε=10⁻² for grid N=30,100 and wells N=5,30).",]
(Path(__file__).parent / "A2_claims_registry.md").write_text("\n".join(rows) + "\n")
print(len(used), "macros;", len(unm), "unmapped", unm)
