"""Descriptive, exhaustive same-estimator TBMD/POD comparisons from canonical E2.

No experiments or hyperparameters are changed. Counts are not independent trials,
p-values, or a test of all possible classical methods. Outputs are internal only.
"""
import hashlib
from pathlib import Path

import numpy as np
import pandas as pd

STRATA = ["protocol", "sensing", "regime", "N"]
KEYS = STRATA + ["fold", "seed"]


def compare_pair(left, right, metric, expected_folds=10, expected_seeds=20):
    """Require complete labelled pairs before summarising seeds within folds."""
    for frame in (left, right):
        if frame.empty or frame.duplicated(KEYS).any():
            raise ValueError("empty or duplicate comparison keys")
        if not np.isfinite(frame[metric]).all():
            raise ValueError("nonfinite metric")
    columns = KEYS + ["rank", "m", metric]
    paired = left[columns].merge(right[columns], on=KEYS, how="outer",
                                validate="one_to_one", indicator=True,
                                suffixes=("_tbmd", "_baseline"))
    if not paired._merge.eq("both").all():
        raise ValueError("unmatched fold/seed/budget labels")
    for name in ("rank", "m"):
        a, b = paired[name + "_tbmd"], paired[name + "_baseline"]
        if not (a.eq(b) | (a.isna() & b.isna())).all():
            raise ValueError("rank or scalar measurement budget mismatch")
    sizes = paired.groupby(STRATA + ["fold"]).size()
    for key, count in sizes.items():
        expected = expected_seeds if key[2] == "random" else 1
        if count != expected:
            raise ValueError("unexpected seed count")
    metrics = [metric + "_tbmd", metric + "_baseline"]
    folds = paired.groupby(STRATA + ["fold"], as_index=False)[metrics].median()
    records = []
    for key, frame in folds.groupby(STRATA, sort=True):
        if len(frame) != expected_folds:
            raise ValueError("unexpected fold count")
        a, b = frame[metrics[0]].to_numpy(), frame[metrics[1]].to_numpy()
        ties = np.isclose(a, b, rtol=1e-10, atol=1e-12)
        am, bm = float(a.mean()), float(b.mean())
        verdict = "tie" if np.isclose(am, bm, rtol=1e-10, atol=1e-12) else (
            "win" if am < bm else "loss")
        records.append(dict(zip(STRATA, key)) | dict(
            metric=metric, tbmd_mean=am, tbmd_sd=float(a.std(ddof=1)),
            baseline_mean=bm, baseline_sd=float(b.std(ddof=1)),
            fold_wins=int(((a < b) & ~ties).sum()), fold_ties=int(ties.sum()),
            fold_losses=int(((a > b) & ~ties).sum()), mean_verdict=verdict,
            comparison="same observations" if key[2] != "optimised" else
                       "same budget; basis-specific observations"))
    return pd.DataFrame(records)


def main():
    destination = Path(__file__).resolve().parent
    root = destination.parents[3]
    source = root / "studies/brugge_sparse_sensing/outputs/e2_summary.csv"
    data = pd.read_csv(source)
    data = data[data.basis.isin(["TBMD", "POD", "POD-E"])].copy()
    data["regime"] = data.placement.where(
        ~data.placement.str.startswith(("QR-", "DG-")), "optimised")
    results = []
    for estimator in ("LS", "L1", "projection"):
        for baseline in ("POD", "POD-E"):
            left = data[(data.estimator == estimator) & (data.basis == "TBMD")]
            right = data[(data.estimator == estimator) & (data.basis == baseline)]
            for metric in ("rmse_p", "rmse_so"):
                result = compare_pair(left, right, metric)
                result["estimator"] = estimator
                result["baseline"] = baseline
                results.append(result)
    result = pd.concat(results, ignore_index=True)
    result.to_csv(destination / "superiority_comparisons.csv", index=False)
    counts = result.groupby(["comparison", "baseline", "estimator", "metric",
                             "mean_verdict"]).size().unstack(fill_value=0)
    counts = counts.reindex(columns=["win", "tie", "loss"], fill_value=0)
    counts.to_csv(destination / "superiority_counts.csv")
    lines = ["# Complete canonical E2 superiority check", "",
             "Generated by `superiority_audit.py`; do not edit this report manually.",
             f"Input SHA-256: `{hashlib.sha256(source.read_bytes()).hexdigest()}`.",
             "", f"All {len(result)} defined comparisons retained; none selected by outcome.",
             "A stratum is protocol × sensing regime × budget × estimator × baseline × property.",
             "Mean verdict uses ten fold means (random: median of 20 seeds within fold).",
             "All fold/seed/rank/scalar-budget pairings are checked; metrics must be finite.",
             "Tie tolerance: rtol=1e-10, atol=1e-12. Lower RMSE is better.",
             "Counts below describe this finite sweep, not independent statistical trials or all classical algorithms.",
             "Optimised placements are end-to-end comparisons, not identical sensor sets.",
             "Pressure units remain conditional on author export-unit confirmation.", "",
             "| Comparison | Baseline | Estimator | Metric | TBMD wins | Ties | Losses |",
             "|---|---|---|---|---:|---:|---:|"]
    for key, row in counts.iterrows():
        lines.append("| " + " | ".join(map(str, key)) +
                     f" | {row['win']} | {row['tie']} | {row['loss']} |")
    lines += ["", "Detailed means, sample SDs and fold win/tie/loss counts: `superiority_comparisons.csv`.",
              "This audit does not pool costs, noise levels or E8 with accuracy into an overall score.",
              "No hyperparameter was retuned; this is a new analysis of verified stored outputs, not a new raw-data experiment."]
    (destination / "superiority_summary.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
