"""Build a Word copy of the author-confirmed statement, not an Elsevier Tool export."""

from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, RGBColor

ROOT = Path(__file__).resolve().parent
text = (ROOT / "declaration_of_competing_interest.txt").read_text().strip()
text = text.removeprefix("Declaration of competing interest").strip()
document = Document()
section = document.sections[0]
section.top_margin = section.bottom_margin = Inches(1)
section.left_margin = section.right_margin = Inches(1)
for name in ("Normal", "Title"):
    style = document.styles[name]
    style.font.name = "Arial"
    style.font.color.rgb = RGBColor(0, 0, 0)
document.styles["Normal"].font.size = Pt(11)
document.styles["Title"].font.size = Pt(18)
for tree in (document.styles.element, document.element):
    for border in tree.xpath(".//w:pBdr"):
        border.getparent().remove(border)
document.add_paragraph("Declaration of competing interest", style="Title")
document.add_paragraph(text)
document.core_properties.title = "Declaration of competing interest"
document.core_properties.author = ""
document.core_properties.comments = (
    "Locally generated from the author-confirmed canonical statement. "
    "Not generated by the Elsevier Declaration Tool."
)
document.save(ROOT / "declaration_of_competing_interest.docx")
print("Created author-confirmed Word declaration; official tool origin is not claimed.")
